name: CI
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions: {}

jobs:
  Ubuntu:
    uses: named-data/actions/.github/workflows/jenkins-script-ubuntu.yml@v1
  macOS:
    uses: named-data/actions/.github/workflows/jenkins-script-macos.yml@v1
  PPA:
    uses: named-data/actions/.github/workflows/ppa.yml@v1
    with:
      extra-deps: libboost-iostreams-dev
